/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#include <m8c.h>
/*
*   PSoCGPIOINT.h
*   Data: 04 June, 2002
*   Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
*
*  This file is generated by the Device Editor on Application Generation.
*  It contains equates that are useful in writing code relating to GPIO
*  related values.
*  
*  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
*  Edits to this file will not be preserved.
*/
// int4 address and mask defines
#pragma	ioport	int4_Data_ADDR:	0x4
BYTE			int4_Data_ADDR;
#pragma	ioport	int4_DriveMode_0_ADDR:	0x104
BYTE			int4_DriveMode_0_ADDR;
#pragma	ioport	int4_DriveMode_1_ADDR:	0x105
BYTE			int4_DriveMode_1_ADDR;
#pragma	ioport	int4_DriveMode_2_ADDR:	0x7
BYTE			int4_DriveMode_2_ADDR;
#pragma	ioport	int4_GlobalSelect_ADDR:	0x6
BYTE			int4_GlobalSelect_ADDR;
#pragma	ioport	int4_IntCtrl_0_ADDR:	0x106
BYTE			int4_IntCtrl_0_ADDR;
#pragma	ioport	int4_IntCtrl_1_ADDR:	0x107
BYTE			int4_IntCtrl_1_ADDR;
#pragma	ioport	int4_IntEn_ADDR:	0x5
BYTE			int4_IntEn_ADDR;
#define int4_MASK 0x20
// int3 address and mask defines
#pragma	ioport	int3_Data_ADDR:	0x4
BYTE			int3_Data_ADDR;
#pragma	ioport	int3_DriveMode_0_ADDR:	0x104
BYTE			int3_DriveMode_0_ADDR;
#pragma	ioport	int3_DriveMode_1_ADDR:	0x105
BYTE			int3_DriveMode_1_ADDR;
#pragma	ioport	int3_DriveMode_2_ADDR:	0x7
BYTE			int3_DriveMode_2_ADDR;
#pragma	ioport	int3_GlobalSelect_ADDR:	0x6
BYTE			int3_GlobalSelect_ADDR;
#pragma	ioport	int3_IntCtrl_0_ADDR:	0x106
BYTE			int3_IntCtrl_0_ADDR;
#pragma	ioport	int3_IntCtrl_1_ADDR:	0x107
BYTE			int3_IntCtrl_1_ADDR;
#pragma	ioport	int3_IntEn_ADDR:	0x5
BYTE			int3_IntEn_ADDR;
#define int3_MASK 0x8
// led3 address and mask defines
#pragma	ioport	led3_Data_ADDR:	0x0
BYTE			led3_Data_ADDR;
#pragma	ioport	led3_DriveMode_0_ADDR:	0x100
BYTE			led3_DriveMode_0_ADDR;
#pragma	ioport	led3_DriveMode_1_ADDR:	0x101
BYTE			led3_DriveMode_1_ADDR;
#pragma	ioport	led3_DriveMode_2_ADDR:	0x3
BYTE			led3_DriveMode_2_ADDR;
#pragma	ioport	led3_GlobalSelect_ADDR:	0x2
BYTE			led3_GlobalSelect_ADDR;
#pragma	ioport	led3_IntCtrl_0_ADDR:	0x102
BYTE			led3_IntCtrl_0_ADDR;
#pragma	ioport	led3_IntCtrl_1_ADDR:	0x103
BYTE			led3_IntCtrl_1_ADDR;
#pragma	ioport	led3_IntEn_ADDR:	0x1
BYTE			led3_IntEn_ADDR;
#define led3_MASK 0x2
// int13 address and mask defines
#pragma	ioport	int13_Data_ADDR:	0x4
BYTE			int13_Data_ADDR;
#pragma	ioport	int13_DriveMode_0_ADDR:	0x104
BYTE			int13_DriveMode_0_ADDR;
#pragma	ioport	int13_DriveMode_1_ADDR:	0x105
BYTE			int13_DriveMode_1_ADDR;
#pragma	ioport	int13_DriveMode_2_ADDR:	0x7
BYTE			int13_DriveMode_2_ADDR;
#pragma	ioport	int13_GlobalSelect_ADDR:	0x6
BYTE			int13_GlobalSelect_ADDR;
#pragma	ioport	int13_IntCtrl_0_ADDR:	0x106
BYTE			int13_IntCtrl_0_ADDR;
#pragma	ioport	int13_IntCtrl_1_ADDR:	0x107
BYTE			int13_IntCtrl_1_ADDR;
#pragma	ioport	int13_IntEn_ADDR:	0x5
BYTE			int13_IntEn_ADDR;
#define int13_MASK 0x8
// in5 address and mask defines
#pragma	ioport	in5_Data_ADDR:	0x0
BYTE			in5_Data_ADDR;
#pragma	ioport	in5_DriveMode_0_ADDR:	0x100
BYTE			in5_DriveMode_0_ADDR;
#pragma	ioport	in5_DriveMode_1_ADDR:	0x101
BYTE			in5_DriveMode_1_ADDR;
#pragma	ioport	in5_DriveMode_2_ADDR:	0x3
BYTE			in5_DriveMode_2_ADDR;
#pragma	ioport	in5_GlobalSelect_ADDR:	0x2
BYTE			in5_GlobalSelect_ADDR;
#pragma	ioport	in5_IntCtrl_0_ADDR:	0x102
BYTE			in5_IntCtrl_0_ADDR;
#pragma	ioport	in5_IntCtrl_1_ADDR:	0x103
BYTE			in5_IntCtrl_1_ADDR;
#pragma	ioport	in5_IntEn_ADDR:	0x1
BYTE			in5_IntEn_ADDR;
#define in5_MASK 0x20
// led7 address and mask defines
#pragma	ioport	led7_Data_ADDR:	0x0
BYTE			led7_Data_ADDR;
#pragma	ioport	led7_DriveMode_0_ADDR:	0x100
BYTE			led7_DriveMode_0_ADDR;
#pragma	ioport	led7_DriveMode_1_ADDR:	0x101
BYTE			led7_DriveMode_1_ADDR;
#pragma	ioport	led7_DriveMode_2_ADDR:	0x3
BYTE			led7_DriveMode_2_ADDR;
#pragma	ioport	led7_GlobalSelect_ADDR:	0x2
BYTE			led7_GlobalSelect_ADDR;
#pragma	ioport	led7_IntCtrl_0_ADDR:	0x102
BYTE			led7_IntCtrl_0_ADDR;
#pragma	ioport	led7_IntCtrl_1_ADDR:	0x103
BYTE			led7_IntCtrl_1_ADDR;
#pragma	ioport	led7_IntEn_ADDR:	0x1
BYTE			led7_IntEn_ADDR;
#define led7_MASK 0x80
