/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "TX8_2.h"
#include "Counter16_1.h"
#include "PWM8_1.h"

#endif
