;  Generated by PSoC Designer 5.2.2551
;
;
;  dyn_test2INT.asm
;
;  Data: 29 October, 2001
;  Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
;
;  This file is generated by the Device Editor on Application Generation.
;  It contains dispatch code that ensures that interrupt vectors are 
;  serviced by the appropriate ISR depending on the currently active
;  configuration.
;  
;  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
;  Edits to this file will not be preserved.
;
include "PSoCDynamic.inc"
include "m8c.inc"
export	Dispatch_INTERRUPT_11


Dispatch_INTERRUPT_11:
	push	a
	mov		a,0
	tst		[ACTIVE_CONFIG_STATUS+ADC_Config_ADDR_OFF], ADC_Config_BIT
	jnz		Dispatch_INTERRUPT_11_END
	mov		a,4
	tst		[ACTIVE_CONFIG_STATUS+dyn_test2_ADDR_OFF], dyn_test2_BIT
	jnz		Dispatch_INTERRUPT_11_END
	pop		a
	reti
; Stop Code Compressor from breaking table alignment
; The next instruction does not get executed.
	Suspend_CodeCompressor
Dispatch_INTERRUPT_11_END:
	jacc	Dispatch_INTERRUPT_11_TBL
Dispatch_INTERRUPT_11_TBL:
	pop		a
	ljmp	_TX8_2_ISR
	pop		a
	ljmp	_PWM8_1_ISR
; Resume Code Compressor.
; The next instruction does not get executed.
	Resume_CodeCompressor

