;  Generated by PSoC Designer 5.2.2551
;
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_dyn_test2_Bank1
export LoadConfigTBL_dyn_test2_Bank0
export LoadConfigTBL_dyn_test2_Ordered
export UnloadConfigTBL_dyn_test2_Bank1
export UnloadConfigTBL_dyn_test2_Bank0
export ReloadConfigTBL_dyn_test2_Bank1
export ReloadConfigTBL_dyn_test2_Bank0
export LoadConfigTBL_ADC_Config_Bank1
export LoadConfigTBL_ADC_Config_Bank0
export UnloadConfigTBL_ADC_Config_Bank1
export UnloadConfigTBL_ADC_Config_Bank0
export UnloadConfigTBL_Total_Bank1
export UnloadConfigTBL_Total_Bank0
AREA lit(rom, rel)
LoadConfigTBL_ADC_Config_Bank0:
;  Instance name TX8_2, User Module TX8
;       Instance name TX8_2, Block Name TX8(DCB03)
	db		2fh, 00h		;TX8_2_CONTROL_REG  (DCB03CR0)
	db		2dh, 00h		;TX8_2_TX_BUFFER_REG(DCB03DR1)
	db		2eh, 00h		;TX8_2_(DCB03DR2)
	db		ffh
LoadConfigTBL_ADC_Config_Bank1:
;  Instance name TX8_2, User Module TX8
;       Instance name TX8_2, Block Name TX8(DCB03)
	db		2ch, 0dh		;TX8_2_FUNC_REG     (DCB03FN)
	db		2dh, 06h		;TX8_2_INPUT_REG    (DCB03IN)
	db		2eh, 44h		;TX8_2_OUTPUT_REG   (DCB03OU)
	db		ffh
UnloadConfigTBL_ADC_Config_Bank0:
;  Instance name TX8_2, User Module TX8
;       Instance name TX8_2, Block Name TX8(DCB03)
	db		2fh, 00h		;TX8_2_CONTROL_0 (DCB03CR0)
	db		ffh
UnloadConfigTBL_ADC_Config_Bank1:
;  Instance name TX8_2, User Module TX8
;       Instance name TX8_2, Block Name TX8(DCB03)
	db		2ch, 00h		;TX8_2_DIG_BasicFunction (DCB03FN)
	db		2dh, 00h		;TX8_2_DIG_Input (DCB03IN)
	db		2eh, 00h		;TX8_2_DIG_Output (DCB03OU)
	db		ffh

;  Instance name TX8_2, User Module TX8
;       Instance name TX8_2, Block Name TX8(DCB03)
	db		ffh
LoadConfigTBL_dyn_test2_Bank0:
;  Instance name Counter16_1, User Module Counter16
;       Instance name Counter16_1, Block Name CNTR16_LSB(DBB00)
	db		23h, 00h		;Counter16_1_CONTROL_LSB_REG(DBB00CR0)
	db		21h, dbh		;Counter16_1_PERIOD_LSB_REG(DBB00DR1)
	db		22h, 00h		;Counter16_1_COMPARE_LSB_REG(DBB00DR2)
;       Instance name Counter16_1, Block Name CNTR16_MSB(DBB01)
	db		27h, 00h		;Counter16_1_CONTROL_MSB_REG(DBB01CR0)
	db		25h, 05h		;Counter16_1_PERIOD_MSB_REG(DBB01DR1)
	db		26h, 00h		;Counter16_1_COMPARE_MSB_REG(DBB01DR2)
;  Instance name PWM8_1, User Module PWM8
;       Instance name PWM8_1, Block Name PWM8(DCB03)
	db		2fh, 00h		;PWM8_1_CONTROL_REG(DCB03CR0)
	db		2dh, 1ch		;PWM8_1_PERIOD_REG(DCB03DR1)
	db		2eh, 0eh		;PWM8_1_COMPARE_REG(DCB03DR2)
;  Global Register values Bank 0
	db		60h, 09h		; AnalogColumnInputSelect register (AMX_IN)
	db		64h, 00h		; AnalogComparatorControl0 register (CMP_CR0)
	db		66h, 00h		; AnalogComparatorControl1 register (CMP_CR1)
	db		e6h, 00h		; DecimatorControl_0 register (DEC_CR0)
	db		e7h, 00h		; DecimatorControl_1 register (DEC_CR1)
	db		d6h, 00h		; I2CConfig register (I2CCFG)
	db		62h, 00h		; PWM_Control register (PWM_CR)
	db		b0h, 04h		; Row_0_InputMux register (RDI0RI)
	db		b1h, 00h		; Row_0_InputSync register (RDI0SYN)
	db		b2h, 00h		; Row_0_LogicInputAMux register (RDI0IS)
	db		b3h, 33h		; Row_0_LogicSelect_0 register (RDI0LT0)
	db		b4h, 33h		; Row_0_LogicSelect_1 register (RDI0LT1)
	db		b5h, 14h		; Row_0_OutputDrive_0 register (RDI0SRO0)
	db		b6h, 12h		; Row_0_OutputDrive_1 register (RDI0SRO1)
	db		ffh
LoadConfigTBL_dyn_test2_Bank1:
;  Instance name Counter16_1, User Module Counter16
;       Instance name Counter16_1, Block Name CNTR16_LSB(DBB00)
	db		20h, 01h		;Counter16_1_FUNC_LSB_REG(DBB00FN)
	db		21h, 15h		;Counter16_1_INPUT_LSB_REG(DBB00IN)
	db		22h, 40h		;Counter16_1_OUTPUT_LSB_REG(DBB00OU)
;       Instance name Counter16_1, Block Name CNTR16_MSB(DBB01)
	db		24h, 21h		;Counter16_1_FUNC_MSB_REG(DBB01FN)
	db		25h, 35h		;Counter16_1_INPUT_MSB_REG(DBB01IN)
	db		26h, 40h		;Counter16_1_OUTPUT_MSB_REG(DBB01OU)
;  Instance name PWM8_1, User Module PWM8
;       Instance name PWM8_1, Block Name PWM8(DCB03)
	db		2ch, 21h		;PWM8_1_FUNC_REG(DCB03FN)
	db		2dh, 16h		;PWM8_1_INPUT_REG(DCB03IN)
	db		2eh, 47h		;PWM8_1_OUTPUT_REG(DCB03OU)
;  Global Register values Bank 1
	db		61h, 00h		; AnalogClockSelect1 register (CLK_CR1)
	db		60h, 00h		; AnalogColumnClockSelect register (CLK_CR0)
	db		62h, 00h		; AnalogIOControl_0 register (ABF_CR0)
	db		67h, 33h		; AnalogLUTControl0 register (ALT_CR0)
	db		64h, 00h		; ComparatorGlobalOutEn register (CMP_GO_EN)
	db		d1h, 00h		; GlobalDigitalInterconnect_Drive_Even_Input register (GDI_E_IN)
	db		d3h, 00h		; GlobalDigitalInterconnect_Drive_Even_Output register (GDI_E_OU)
	db		d0h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Input register (GDI_O_IN)
	db		d2h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Output register (GDI_O_OU)
	db		e1h, 5ch		; OscillatorControl_1 register (OSC_CR1)
	db		e2h, 00h		; OscillatorControl_2 register (OSC_CR2)
	db		dfh, 31h		; OscillatorControl_3 register (OSC_CR3)
	db		deh, 02h		; OscillatorControl_4 register (OSC_CR4)
	db		ddh, 00h		; OscillatorGlobalBusEnableControl register (OSC_GO_EN)
	db		ffh
AREA psoc_config(rom, rel)
LoadConfigTBL_dyn_test2_Ordered:
;  Ordered Global Register values
	M8C_SetBank0
	mov	reg[00h], 00h		; Port_0_Data register (PRT0DR)
	M8C_SetBank1
	mov	reg[00h], cah		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], 15h		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[03h], 15h		; Port_0_DriveMode_2 register (PRT0DM2)
	mov	reg[02h], 4ah		; Port_0_GlobalSelect register (PRT0GS)
	M8C_SetBank1
	mov	reg[02h], 00h		; Port_0_IntCtrl_0 register (PRT0IC0)
	mov	reg[03h], 00h		; Port_0_IntCtrl_1 register (PRT0IC1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	mov	reg[04h], 00h		; Port_1_Data register (PRT1DR)
	M8C_SetBank1
	mov	reg[04h], 01h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], d6h		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[07h], d6h		; Port_1_DriveMode_2 register (PRT1DM2)
	mov	reg[06h], 01h		; Port_1_GlobalSelect register (PRT1GS)
	M8C_SetBank1
	mov	reg[06h], 28h		; Port_1_IntCtrl_0 register (PRT1IC0)
	mov	reg[07h], 28h		; Port_1_IntCtrl_1 register (PRT1IC1)
	M8C_SetBank0
	mov	reg[05h], 28h		; Port_1_IntEn register (PRT1IE)
	M8C_SetBank0
	ret
AREA lit(rom, rel)
ReloadConfigTBL_dyn_test2_Bank0:
;  Instance name Counter16_1, User Module Counter16
;       Instance name Counter16_1, Block Name CNTR16_LSB(DBB00)
	db		23h, 00h		;Counter16_1_CONTROL_LSB_REG(DBB00CR0)
	db		21h, dbh		;Counter16_1_PERIOD_LSB_REG(DBB00DR1)
	db		22h, 00h		;Counter16_1_COMPARE_LSB_REG(DBB00DR2)
;       Instance name Counter16_1, Block Name CNTR16_MSB(DBB01)
	db		27h, 00h		;Counter16_1_CONTROL_MSB_REG(DBB01CR0)
	db		25h, 05h		;Counter16_1_PERIOD_MSB_REG(DBB01DR1)
	db		26h, 00h		;Counter16_1_COMPARE_MSB_REG(DBB01DR2)
;  Instance name PWM8_1, User Module PWM8
;       Instance name PWM8_1, Block Name PWM8(DCB03)
	db		2fh, 00h		;PWM8_1_CONTROL_REG(DCB03CR0)
	db		2dh, 1ch		;PWM8_1_PERIOD_REG(DCB03DR1)
	db		2eh, 0eh		;PWM8_1_COMPARE_REG(DCB03DR2)
	db		ffh
ReloadConfigTBL_dyn_test2_Bank1:
;  Instance name Counter16_1, User Module Counter16
;       Instance name Counter16_1, Block Name CNTR16_LSB(DBB00)
	db		20h, 01h		;Counter16_1_FUNC_LSB_REG(DBB00FN)
	db		21h, 15h		;Counter16_1_INPUT_LSB_REG(DBB00IN)
	db		22h, 40h		;Counter16_1_OUTPUT_LSB_REG(DBB00OU)
;       Instance name Counter16_1, Block Name CNTR16_MSB(DBB01)
	db		24h, 21h		;Counter16_1_FUNC_MSB_REG(DBB01FN)
	db		25h, 35h		;Counter16_1_INPUT_MSB_REG(DBB01IN)
	db		26h, 40h		;Counter16_1_OUTPUT_MSB_REG(DBB01OU)
;  Instance name PWM8_1, User Module PWM8
;       Instance name PWM8_1, Block Name PWM8(DCB03)
	db		2ch, 21h		;PWM8_1_FUNC_REG(DCB03FN)
	db		2dh, 16h		;PWM8_1_INPUT_REG(DCB03IN)
	db		2eh, 47h		;PWM8_1_OUTPUT_REG(DCB03OU)
	db		ffh
UnloadConfigTBL_dyn_test2_Bank0:
;  Instance name Counter16_1, User Module Counter16
;       Instance name Counter16_1, Block Name CNTR16_LSB(DBB00)
	db		23h, 00h		;Counter16_1_CONTROL_0 (DBB00CR0)
;       Instance name Counter16_1, Block Name CNTR16_MSB(DBB01)
	db		27h, 00h		;Counter16_1_CONTROL_0 (DBB01CR0)
;  Instance name PWM8_1, User Module PWM8
;       Instance name PWM8_1, Block Name PWM8(DCB03)
	db		2fh, 00h		;PWM8_1_CONTROL_0 (DCB03CR0)
	db		ffh
UnloadConfigTBL_dyn_test2_Bank1:
;  Instance name Counter16_1, User Module Counter16
;       Instance name Counter16_1, Block Name CNTR16_LSB(DBB00)
	db		20h, 00h		;Counter16_1_DIG_BasicFunction (DBB00FN)
	db		21h, 00h		;Counter16_1_DIG_Input (DBB00IN)
	db		22h, 00h		;Counter16_1_DIG_Output (DBB00OU)
;       Instance name Counter16_1, Block Name CNTR16_MSB(DBB01)
	db		24h, 00h		;Counter16_1_DIG_BasicFunction (DBB01FN)
	db		25h, 00h		;Counter16_1_DIG_Input (DBB01IN)
	db		26h, 00h		;Counter16_1_DIG_Output (DBB01OU)
;  Instance name PWM8_1, User Module PWM8
;       Instance name PWM8_1, Block Name PWM8(DCB03)
	db		2ch, 00h		;PWM8_1_DIG_BasicFunction (DCB03FN)
	db		2dh, 00h		;PWM8_1_DIG_Input (DCB03IN)
	db		2eh, 00h		;PWM8_1_DIG_Output (DCB03OU)
	db		ffh

;  Instance name Counter16_1, User Module Counter16
;       Instance name Counter16_1, Block Name CNTR16_LSB(DBB00)
;       Instance name Counter16_1, Block Name CNTR16_MSB(DBB01)
;  Instance name PWM8_1, User Module PWM8
;       Instance name PWM8_1, Block Name PWM8(DCB03)
	db		ffh
UnloadConfigTBL_Total_Bank0:
;  Block DBB00
	db		23h, 00h		; CONTROL_0 register (DBB00CR0)
;  Block DBB01
	db		27h, 00h		; CONTROL_0 register (DBB01CR0)
;  Block DCB02
	db		2bh, 00h		; CONTROL_0 register (DCB02CR0)
;  Block DCB03
	db		2fh, 00h		; CONTROL_0 register (DCB03CR0)
;  Block ACE00
;  Block ASE10
;  Block ACE01
;  Block ASE11
	db		ffh
UnloadConfigTBL_Total_Bank1:
;  Block DBB00
	db		20h, 00h		; DIG_BasicFunction register (DBB00FN)
	db		21h, 00h		; DIG_Input register (DBB00IN)
	db		22h, 00h		; DIG_Output register (DBB00OU)
;  Block DBB01
	db		24h, 00h		; DIG_BasicFunction register (DBB01FN)
	db		25h, 00h		; DIG_Input register (DBB01IN)
	db		26h, 00h		; DIG_Output register (DBB01OU)
;  Block DCB02
	db		28h, 00h		; DIG_BasicFunction register (DCB02FN)
	db		29h, 00h		; DIG_Input register (DCB02IN)
	db		2ah, 00h		; DIG_Output register (DCB02OU)
;  Block DCB03
	db		2ch, 00h		; DIG_BasicFunction register (DCB03FN)
	db		2dh, 00h		; DIG_Input register (DCB03IN)
	db		2eh, 00h		; DIG_Output register (DCB03OU)
;  Block ACE00
;  Block ASE10
;  Block ACE01
;  Block ASE11
	db		ffh


; PSoC Configuration file trailer PsocConfig.asm
