/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
extern void LoadConfig_dyn_test2( void);
extern void ReloadConfig_dyn_test2( void);
extern void UnloadConfig_dyn_test2( void);
extern char Isdyn_test2Loaded( void);
extern void LoadConfig_ADC_Config( void);
extern void UnloadConfig_ADC_Config( void);
extern char IsADC_ConfigLoaded( void);
extern void UnloadConfig_Total( void);
