;  Generated by PSoC Designer 5.2.2551
;
;
;  dyn_test2Dynamic.asm
;
;  Data: 11 June, 2004
;  Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
;
;  This file is generated by the Device Editor on Application Generation.
;  It contains functions that can be used to test the state of the 
;  currently active configuration.
;  
;  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
;  Edits to this file will not be preserved.
;
include "m8c.inc"
include "memory.inc"
include "PSoCDynamic.inc"
export Isdyn_test2Loaded
export _Isdyn_test2Loaded
export IsADC_ConfigLoaded
export _IsADC_ConfigLoaded
Isdyn_test2Loaded:
_Isdyn_test2Loaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+dyn_test2_ADDR_OFF], dyn_test2_BIT
	jz		dyn_test2IsNotLoaded
	mov		a, 1
dyn_test2IsNotLoaded:
	ret

IsADC_ConfigLoaded:
_IsADC_ConfigLoaded:
	RAM_SETPAGE_CUR >ACTIVE_CONFIG_STATUS
	mov		a, 0
	tst		[ACTIVE_CONFIG_STATUS+ADC_Config_ADDR_OFF], ADC_Config_BIT
	jz		ADC_ConfigIsNotLoaded
	mov		a, 1
ADC_ConfigIsNotLoaded:
	ret

